title: Mr
author: Ikechukwu Onuorah
email: onuorah.ikechukwuvictor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Fullstack developer and a Git expert
theme: minima

# social links
twitter_username: LENEVER # DO NOT include the @ character, or else the build will fail!
github_username:  Lenever # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
